POST http://localhost:3000/api/v1/customers HTTP/1.1
content-type: application/json

{
  "name": "Oscar1",
  "lastName": "Fuentes",
  "phone": "480",
  "user":{
    "email": "santo1@mail.com",
    "password": "12345678"
  }
}
